# Generated by Django 5.0 on 2023-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
