# Generated by Django 5.0 on 2023-12-13 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_alter_showtheme_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={},
        ),
        migrations.AlterModelOptions(
            name="planetariumdome",
            options={},
        ),
        migrations.AlterModelOptions(
            name="showtheme",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
    ]
